### ISSUE TITLE
alignleft and alignright are switched on RTL

### ISSUE THREAD

**Issue by joyously** [WordPress/twentynineteen#325]
In RTL mode, alignleft is on the right and alignright is on the left. These should not change with RTL.

![rtl-image-alignement](https://user-images.githubusercontent.com/7957680/47517872-1d46df00-d84f-11e8-920f-eb08b58d6082.jpg)

**Comment by kjellr** [comment]
Should be fixed as of #425. Block alignments may still be a little off until 
https://github.com/WordPress/gutenberg/pull/11293 is merged into Gutenberg. 👍

**Comment by joyously** [comment]
**This is only partially fixed.**
stand-alone left is OK
stand-alone right is on the right, but margin is also
captioned left is on the right
captioned right is on the left

![rtl-switch](https://user-images.githubusercontent.com/7957680/47947540-613f8100-deec-11e8-9168-bb0b603a59c0.jpg)

**Comment by allancole** [comment]
Reopening as per @joyously's note above.
